spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  profiles: local
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
  thymeleaf:
    cache: false

  redis:
    host: 114.115.178.17
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: 10000
        max-idle: 10
        min-idle: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB


