spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  profiles: local
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
  thymeleaf:
    cache: false

