spring:
  profiles.active: local
---
spring:
  profiles: local
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
